const output=document.querySelector('#output');const command=document.querySelector('#command');const buttons=document.querySelectorAll('.nav-btn');const pages=document.querySelectorAll('.page');
function line(text,type='system'){const el=document.createElement('div');el.className=`line ${type}`;el.textContent=text;output?.appendChild(el);if(output)output.scrollTop=output.scrollHeight}
function boot(){['VOIDNET relay booting...','Loading ghost protocol... OK','Verifying encryption keys... OK','Mapping relay topology... OK','Connection established.','Welcome back, root.'].forEach((x,i)=>setTimeout(()=>line(x,i===5?'success':'system'),i*130));}
const commands={help:'show commands',ls:'list ghost files',whoami:'show identity',scan:'scan fake relay nodes',trace:'trace a route',status:'show system status',access:'open a simulated node',clear:'clear output',reboot:'restart the relay'};
function run(raw){const value=raw.trim();if(!value)return;line(`root@ghost:~$ ${value}`,'command');const [cmd,...args]=value.toLowerCase().split(/\s+/);if(cmd==='help'){line('AVAILABLE COMMANDS:');Object.entries(commands).forEach(([k,v])=>line(`  ${k.padEnd(9)} ${v}`,'success'))}else if(cmd==='ls'){['bin/','etc/','home/','root/keys/','mission.log'].forEach(x=>line(`  ${x}`,'success'))}else if(cmd==='whoami'){line('identity: root','success');line('access: tier-9','success');line('host: ghost-alpha','success')}else if(cmd==='scan'){line('Scanning simulated network...','warning');['relay-03 // ONLINE','archive-2 // COMPROMISED','oracle-9 // MONITORED','vault-4 // ONLINE'].forEach((x,i)=>setTimeout(()=>line(`  ${x}`,'success'),i*140))}else if(cmd==='trace'){line(`Tracing ${args[0]||'relay-03'}...`,'warning');setTimeout(()=>line('Route verified // tunnel stable','success'),300)}else if(cmd==='status'){['relay: nominal','latency: 4ms','cipher: active','firewall: stable'].forEach(x=>line(x,'success'))}else if(cmd==='access'){line(`Simulating access handshake: ${args[0]||'vault-4'}`,'warning');setTimeout(()=>line('Access granted (simulation only).','success'),350)}else if(cmd==='clear'){output.innerHTML='';boot()}else if(cmd==='reboot'){line('Restarting simulated relay...','warning');setTimeout(()=>line('Relay restarted successfully.','success'),350)}else line(`command not found: ${cmd}`,'error')}
command?.addEventListener('keydown',e=>{if(e.key==='Enter'){run(command.value);command.value=''}});
function showPage(id){buttons.forEach(b=>b.classList.toggle('active',b.dataset.page===id));pages.forEach(p=>p.classList.toggle('active',p.id===id));if(id==='console')command?.focus()}
buttons.forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('[data-page-link]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.pageLink)));document.querySelectorAll('.toggle').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('on');b.textContent=b.classList.contains('on')?'ON':'OFF'}));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>line?.(`Action ${b.dataset.action} executed in simulation.`,'success')));
const canvas=document.querySelector('#matrix'),ctx=canvas?.getContext('2d');let drops=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;drops=Array(Math.ceil(innerWidth/16)).fill(0).map(()=>Math.random()*-40)}function matrix(){ctx.fillStyle='rgba(2,9,12,.09)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.font='15px monospace';drops.forEach((y,i)=>{ctx.fillStyle=i%4?'#187f65':'#69ffd2';ctx.fillText('01#X+*'[Math.floor(Math.random()*6)],i*16,y*16);if(y*16>canvas.height&&Math.random()>.975)drops[i]=0;drops[i]++})}addEventListener('resize',resize);resize();setInterval(matrix,75);boot();if(!output){console.warn('Console output is only available on the Console page.')}else setTimeout(()=>line('Type "help" to begin.','system'),900);
